export const MAIN_PATH = () => '/';
export const AUTH_PATH = () => '/auth';
export const SEARCH_PATH = (searchWord: string) => `/search/${searchWord}`;
export const USER_PATH = (userEmail: string) => `/user/${userEmail}`;
export const BOARD_PATH = () => '/board';
export const BOARD_DETAIL_PATH = (boardNumber: string | number) => `detail/${boardNumber}`;
export const BOARD_WRITE_PATH = () => 'write';
export const BOARD_UPDATE_PATH = (boardNumber: string | number) => `update/${boardNumber}`;
export const BLOG_PATH = () => '/blog';
export const COMMUNITY_PATH = () => '/community';
export const POST_PATH = () => '/post';
export const POST_DETAIL_PATH = (postNumber: string | number) => `detail/${postNumber}`;
export const POST_WRITE_PATH = () => 'write';
export const POST_UPDATE_PATH = (postNumber: string | number) => `update/${postNumber}`;
export const EMPLOYMENT_PATH = (devCategoryNumber: string | number) => `/employment/${devCategoryNumber}`;
export const NOTICE_PATH = () => '/notice';
export const NOTICE_DETAIL_PATH = (noticeNumber: string | number) => `detail/${noticeNumber}`;
export const NOTICE_REGISTRATION_PATH = (corporationNumber: string | number) => `registration/${corporationNumber}`;
export const NOTICE_UPDATE_PATH = () => (noticeNumber: string | number) => `update/${noticeNumber}`;
export const MAP_PATH = (userEmail?: string) => userEmail ? `/map/${userEmail}` : '/map';
export const CORPORATION_PATH = () => '/corporation';
export const CORPORATION_DETAIL_PATH = (corporationNumber: string | number) => `detail/${corporationNumber}`;
export const CORPORATION_REGISTRATION_PATH = () => 'registration';
export const CORPORATION_MANAGEMENT_PATH = (corporationNumber: string | number) => `management/${corporationNumber}`;
export const CORPORATION_UPDATE_PATH = (corporationNumber: string | number) => `update/${corporationNumber}`;
export const GROUP_PATH = () => '/group';
export const GROPP_DETAIL_PATH = (groupNumber: string | number) => `/group/${groupNumber}`;
export const RESUME_PATH = () => '/resume';
export const RESUME_MANAGEMENT_PATH = (userEmail: string) => `management/${userEmail}`;
export const RESUME_WRITE_PATH = () => 'write';